### ISSUE TITLE
The whole page is scrolling while using up/down arrow key

### ISSUE THREAD

**Issue by mk48** [tsriram/15puzzle#2]
Please disable the scroll behaviour if possible, because the page is getting scrolled while pressing up/down arrow key. (Its normal behaviour on the web that up/down arrow key for scrolling).

**Comment by tsriram** [comment]
@mk48 sorry, I missed this earlier :(

Do you mean the content of the page is scrolling? Or the browser's address bar moving up & down? Can you please post a screen recoding?

**Comment by mk48** [comment]
Content of the page is scrolling.

![num puzzle](https://user-images.githubusercontent.com/3082469/96337264-6ed37e80-10a3-11eb-9592-dec266452954.gif)

**Comment by tsriram** [comment]
@mk48 thanks for the screen recording. This should be fixed now.

Thanks again for reporting this issue :)

**Comment by mk48** [comment]
Thanks for fixing this. it's working great now. 👍✨
