### ISSUE TITLE
Completion timer does not reset properly

### ISSUE THREAD

**Issue by novacourtois** [tsriram/15puzzle#3]
After playing multiple games, the completion time keps getting appended instead of reset.
<img width="1680" alt="Screen Shot 2020-10-09 at 21 06 08" src="https://user-images.githubusercontent.com/2448346/95645461-e04c7500-0a84-11eb-8152-13cdb850d590.png">

**Comment by tsriram** [comment]
@novacourtois thanks for reporting this! I'll take a look at it this weekend hopefully :)

**Comment by tsriram** [comment]
@novacourtois this should be fixed now. Please let me know if you come across this.

And thank you again for reporting this 👍
